// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eLDA_pass_b_fast
List eLDA_pass_b_fast(List mod, IntegerMatrix count, IntegerVector ndsum, int NZ, int V, int K, double alpha, double beta);
RcppExport SEXP _mlstm_eLDA_pass_b_fast(SEXP modSEXP, SEXP countSEXP, SEXP ndsumSEXP, SEXP NZSEXP, SEXP VSEXP, SEXP KSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type count(countSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndsum(ndsumSEXP);
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(eLDA_pass_b_fast(mod, count, ndsum, NZ, V, K, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// stm_multi_hier_vi_parallel
List stm_multi_hier_vi_parallel(List mod, IntegerMatrix docs, NumericMatrix y, IntegerVector ndsum, int NZ, int V, int K, int J, double alpha, double beta, NumericVector mu, double upsilon, NumericMatrix Omega, bool update_sigma, int tau, bool exact_second_moment, bool show_progress, int chunk);
RcppExport SEXP _mlstm_stm_multi_hier_vi_parallel(SEXP modSEXP, SEXP docsSEXP, SEXP ySEXP, SEXP ndsumSEXP, SEXP NZSEXP, SEXP VSEXP, SEXP KSEXP, SEXP JSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP muSEXP, SEXP upsilonSEXP, SEXP OmegaSEXP, SEXP update_sigmaSEXP, SEXP tauSEXP, SEXP exact_second_momentSEXP, SEXP show_progressSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type docs(docsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndsum(ndsumSEXP);
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type upsilon(upsilonSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< bool >::type update_sigma(update_sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type exact_second_moment(exact_second_momentSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(stm_multi_hier_vi_parallel(mod, docs, y, ndsum, NZ, V, K, J, alpha, beta, mu, upsilon, Omega, update_sigma, tau, exact_second_moment, show_progress, chunk));
    return rcpp_result_gen;
END_RCPP
}
// stm_vi_parallel
List stm_vi_parallel(List mod, IntegerMatrix docs, NumericVector y, IntegerVector ndsum, int NZ, int V, int K, double alpha, double beta, bool update_sigma, int tau, bool show_progress, int chunk);
RcppExport SEXP _mlstm_stm_vi_parallel(SEXP modSEXP, SEXP docsSEXP, SEXP ySEXP, SEXP ndsumSEXP, SEXP NZSEXP, SEXP VSEXP, SEXP KSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP update_sigmaSEXP, SEXP tauSEXP, SEXP show_progressSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type docs(docsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndsum(ndsumSEXP);
    Rcpp::traits::input_parameter< int >::type NZ(NZSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type update_sigma(update_sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(stm_vi_parallel(mod, docs, y, ndsum, NZ, V, K, alpha, beta, update_sigma, tau, show_progress, chunk));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mlstm_eLDA_pass_b_fast", (DL_FUNC) &_mlstm_eLDA_pass_b_fast, 8},
    {"_mlstm_stm_multi_hier_vi_parallel", (DL_FUNC) &_mlstm_stm_multi_hier_vi_parallel, 18},
    {"_mlstm_stm_vi_parallel", (DL_FUNC) &_mlstm_stm_vi_parallel, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlstm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
