# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' One Gibbs sampling sweep for LDA (collapsed) using document–term list.
#'
#' This function performs a single collapsed Gibbs sampling pass over all
#' non-zero document–term entries. Each (d, v, count) triple is treated as
#' `count` replicated word tokens sharing the same topic assignment.
#'
#' The state is stored in a list `mod` containing:
#'   \describe{
#'     \item{z}{Integer vector of length NZ; topic assignment for each
#'       (d, v, count) triple.}
#'     \item{nd}{D×K integer matrix; document–topic counts.}
#'     \item{nw}{K×V integer matrix; topic–word counts.}
#'     \item{nwsum}{Integer vector of length K; total word count per topic.}
#'   }
#'
#' @param mod List with current sampler state: \code{z}, \code{nd},
#'   \code{nw}, and \code{nwsum} as described above.
#' @param count IntegerMatrix of size NZ×3, where each row is a triple
#'   (d, v, c) with 0-based indices: document index \code{d}, word index
#'   \code{v}, and count \code{c} for that (doc, word) pair.
#' @param ndsum IntegerVector of length D; total token count per document
#'   (i.e., \code{ndsum[d] = sum_k nd(d,k)}). Updated in place.
#' @param NZ Integer, number of non-zero entries (rows in \code{count}
#'   and length of \code{z}).
#' @param V Integer, vocabulary size.
#' @param K Integer, number of topics.
#' @param alpha Scalar Dirichlet prior parameter for document–topic
#'   distributions \eqn{\theta_d} (symmetric).
#' @param beta Scalar Dirichlet prior parameter for topic–word
#'   distributions \eqn{\phi_k} (symmetric).
#'
#' @return A list with updated state:
#'   \describe{
#'     \item{z}{Updated topic assignment vector (length NZ).}
#'     \item{nd}{Updated D×K document–topic counts.}
#'     \item{nw}{Updated K×V topic–word counts.}
#'     \item{nwsum}{Updated total word counts per topic.}
#'   }
#'
eLDA_pass_b_fast <- function(mod, count, ndsum, NZ, V, K, alpha, beta) {
    .Call(`_mlstm_eLDA_pass_b_fast`, mod, count, ndsum, NZ, V, K, alpha, beta)
}

#' Variational inference for multi-output supervised topic models
#' with hierarchical prior.
#'
#' The model includes:
#'   - LDA structure: theta_d ~ Dir(alpha), phi_k ~ Dir(beta)
#'   - Gaussian response: y[d,j] ~ N(zbar_d^T eta_j, sigma_j^2)
#'   - Hierarchical prior:
#'       eta_j ~ N(mu, Lambda^-1)
#'       Lambda ~ inverse-Wishart(upsilon, Omega)
#'
#' @param mod List with model state:
#'   - nd  (D x K) document-topic counts
#'   - nw  (K x V) topic-word counts
#'   - eta (K x J) regression coefficients
#'   - sigma2 (J) noise variances
#' @param docs IntegerMatrix (NZ x 3) with (doc_id, word_id, count).
#' @param y NumericMatrix (D x J) response matrix.
#' @param ndsum IntegerVector (D) document token counts.
#' @param NZ,V,K,J Model dimensions.
#' @param alpha,beta Dirichlet hyperparameters.
#' @param mu NumericVector (K) prior mean.
#' @param upsilon Degrees of freedom for inverse-Wishart.
#' @param Omega Scale matrix for inverse-Wishart.
#' @param update_sigma Logical; update sigma2 or not.
#' @param tau Numeric cutoff for stability.
#' @param exact_second_moment Logical flag (currently not used).
#' @param show_progress Logical; print progress.
#' @param chunk Integer; documents per parallel block.
#'
#' @return A list with updated variational parameters and diagnostics:
#'   \describe{
#'     \item{nd}{D x K integer matrix of document-topic counts.}
#'     \item{nw}{K x V integer matrix of topic-word counts.}
#'     \item{eta}{K x J numeric matrix of regression coefficients.}
#'     \item{sigma2}{Length-J numeric vector of noise variances.}
#'     \item{Lambda_E}{K x K numeric matrix, posterior mean of precision matrix Lambda.}
#'     \item{IW_upsilon_hat}{Numeric scalar, posterior degrees of freedom.}
#'     \item{IW_Omega_hat}{K x K numeric matrix, posterior scale matrix.}
#'     \item{elbo}{Numeric scalar, evidence lower bound.}
#'     \item{label_loglik}{Numeric scalar, supervised log-likelihood term.}
#'   }
stm_multi_hier_vi_parallel <- function(mod, docs, y, ndsum, NZ, V, K, J, alpha, beta, mu, upsilon, Omega, update_sigma = TRUE, tau = 20L, exact_second_moment = FALSE, show_progress = TRUE, chunk = 5000L) {
    .Call(`_mlstm_stm_multi_hier_vi_parallel`, mod, docs, y, ndsum, NZ, V, K, J, alpha, beta, mu, upsilon, Omega, update_sigma, tau, exact_second_moment, show_progress, chunk)
}

#' Variational inference for supervised LDA (single continuous response).
#'
#' The model combines unsupervised topic modeling (LDA) with a Gaussian
#' response on document-level topic proportions.
#'
#' \deqn{y_d \sim N(zbar_d^T eta, sigma^2).}
#'
#' This function performs one variational inference sweep with a parallel
#' document-level E-step and simple updates for the regression parameters.
#'
#' @param mod A list containing the current model state:
#'   \describe{
#'     \item{nd}{D x K matrix of document-topic counts.}
#'     \item{nw}{K x V matrix of topic-word counts.}
#'     \item{eta}{Numeric vector of length K; regression coefficients.}
#'     \item{sigma2}{Scalar noise variance for the Gaussian response.}
#'   }
#' @param docs IntegerMatrix of size NZ x 3, where each row is a triple
#'   (d, v, c) in 0-based indexing: document index d, word index v,
#'   and count c = n_dv. Rows with d outside [0, D-1] are ignored.
#' @param y NumericVector of length D; response y_d for each document.
#' @param ndsum IntegerVector of length D; total token count per document
#'   (that is, ndsum[d] = sum_v n_dv).
#' @param NZ Integer, number of non-zero entries in docs (rows of docs).
#' @param V Integer, vocabulary size.
#' @param K Integer, number of topics.
#' @param alpha Scalar Dirichlet prior parameter for document-topic
#'   distributions theta_d (symmetric prior with parameter alpha).
#' @param beta Scalar Dirichlet prior parameter for topic-word
#'   distributions phi_k (symmetric prior with parameter beta).
#' @param update_sigma Logical; if TRUE, update the noise variance sigma2
#'   from residuals y_d - zbar_d^T eta, otherwise keep sigma2 fixed.
#' @param tau Numeric, log-space cutoff used to prune very small topic
#'   responsibilities phi[d,i,k] for numerical stability and efficiency.
#' @param show_progress Logical; if TRUE, print simple progress output
#'   during the E-step over documents.
#' @param chunk Integer, number of documents to process per parallel
#'   block in the E-step. Larger values reduce overhead but may use
#'   more memory.
#'
#' @return A list with updated variational parameters and diagnostics:
#'   \describe{
#'     \item{nd}{Updated D x K document-topic counts.}
#'     \item{nw}{Updated K x V topic-word counts.}
#'     \item{eta}{Updated K-dimensional regression coefficient vector.}
#'     \item{sigma2}{Updated scalar noise variance.}
#'     \item{elbo}{Scalar evidence lower bound (approximate).}
#'     \item{label_loglik}{Gaussian response log-likelihood component.}
#'   }
#'
stm_vi_parallel <- function(mod, docs, y, ndsum, NZ, V, K, alpha, beta, update_sigma = TRUE, tau = 20L, show_progress = TRUE, chunk = 5000L) {
    .Call(`_mlstm_stm_vi_parallel`, mod, docs, y, ndsum, NZ, V, K, alpha, beta, update_sigma, tau, show_progress, chunk)
}

