# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' One Gibbs sampling sweep for LDA (collapsed) using document–term list.
#'
#' This function performs a single collapsed Gibbs sampling pass over all
#' non-zero document–term entries. Each (d, v, count) triple is treated as
#' `count` replicated word tokens sharing the same topic assignment.
#'
#' The state is stored in a list `mod` containing:
#'   \describe{
#'     \item{z}{Integer vector of length NZ; topic assignment for each
#'       (d, v, count) triple.}
#'     \item{nd}{D×K integer matrix; document–topic counts.}
#'     \item{nw}{K×V integer matrix; topic–word counts.}
#'     \item{nwsum}{Integer vector of length K; total word count per topic.}
#'   }
#'
#' @param mod List with current sampler state: \code{z}, \code{nd},
#'   \code{nw}, and \code{nwsum} as described above.
#' @param count IntegerMatrix of size NZ×3, where each row is a triple
#'   (d, v, c) with 0-based indices: document index \code{d}, word index
#'   \code{v}, and count \code{c} for that (doc, word) pair.
#' @param ndsum IntegerVector of length D; total token count per document
#'   (i.e., \code{ndsum[d] = sum_k nd(d,k)}). Updated in place.
#' @param NZ Integer, number of non-zero entries (rows in \code{count}
#'   and length of \code{z}).
#' @param V Integer, vocabulary size.
#' @param K Integer, number of topics.
#' @param alpha Scalar Dirichlet prior parameter for document–topic
#'   distributions \eqn{\theta_d} (symmetric).
#' @param beta Scalar Dirichlet prior parameter for topic–word
#'   distributions \eqn{\phi_k} (symmetric).
#'
#' @return A list with updated state:
#'   \describe{
#'     \item{z}{Updated topic assignment vector (length NZ).}
#'     \item{nd}{Updated D×K document–topic counts.}
#'     \item{nw}{Updated K×V topic–word counts.}
#'     \item{nwsum}{Updated total word counts per topic.}
#'   }
#'
eLDA_pass_b_fast <- function(mod, count, ndsum, NZ, V, K, alpha, beta) {
    .Call(`_mlstm_eLDA_pass_b_fast`, mod, count, ndsum, NZ, V, K, alpha, beta)
}

#' Variational inference for multi-output supervised LDA with hierarchical prior
#' (parallel E-step over documents).
#'
#' The model is:
#'   - Standard LDA for documents: θ_d ~ Dir(α), φ_k ~ Dir(β).
#'   - Supervised Gaussian layer: y_{d,j} | z̄_d, η_j, σ_j^2 ~ N(z̄_d^T η_j, σ_j^2).
#'   - Hierarchical prior on regression coefficients:
#'         η_j ~ N(μ, Λ^{-1}),   Λ ~ IW(upsilon, Ω).
#'
#' @param mod List with model state:
#'   - nd  (D × K) document-topic counts
#'   - nw  (K × V) topic-word counts
#'   - eta (K × J) regression coefficients η_j
#'   - sigma2 (J)  per-output noise variance σ_j^2
#' @param docs IntegerMatrix (NZ × 3) with 0-based triples (doc_id, word_id, count).
#' @param y    NumericMatrix (D × J) response matrix (NA to skip y_{d,j}).
#' @param ndsum IntegerVector (D) total token count per document.
#' @param NZ,V,K,J Model sizes (#nonzeros, vocabulary size, topics, responses).
#' @param alpha,beta Dirichlet hyperparameters for θ and φ.
#' @param mu    NumericVector (K) prior mean μ for η_j.
#' @param upsilon double, degrees of freedom for inverse-Wishart prior on Λ.
#' @param Omega NumericMatrix (K × K) prior scale matrix for inverse-Wishart.
#' @param update_sigma Logical: update σ_j^2 (true) or keep fixed (false).
#' @param tau  Numeric log-cutoff used to prune small φ entries for stability/speed.
#' @param exact_second_moment Logical: if true, use exact E[z̄ z̄ᵀ]; if false, use X Xᵀ approximation.
#' @param show_progress Logical: print progress information during E-step.
#' @param chunk Number of documents processed per parallel chunk.
#'
#' @return List with updated variational parameters and diagnostics:
#'   - nd            (D × K) updated document-topic counts
#'   - nw            (K × V) updated topic-word counts
#'   - eta           (K × J) posterior mean E_q[η_j]
#'   - eta_se        (K × J) approximate standard errors sqrt(diag Var_q[η_j])
#'   - sigma2        (J) updated noise variances
#'   - Lambda_E      (K × K) expected precision E_q[Λ]
#'   - IW_upsilon_hat scalar posterior dof for inverse-Wishart on Λ
#'   - IW_Omega_hat  (K × K) posterior scale matrix for inverse-Wishart on Λ
#'   - elbo          scalar approximate evidence lower bound
#'   - label_loglik  scalar contribution of supervised likelihood to ELBO
#'
stm_multi_hier_vi_parallel <- function(mod, docs, y, ndsum, NZ, V, K, J, alpha, beta, mu, upsilon, Omega, update_sigma = TRUE, tau = 20L, exact_second_moment = FALSE, show_progress = TRUE, chunk = 5000L) {
    .Call(`_mlstm_stm_multi_hier_vi_parallel`, mod, docs, y, ndsum, NZ, V, K, J, alpha, beta, mu, upsilon, Omega, update_sigma, tau, exact_second_moment, show_progress, chunk)
}

#' Variational inference for supervised LDA (single continuous response).
#'
#' The model combines unsupervised topic modeling (LDA) with a Gaussian
#' response on the document-level topic proportions z̄_d:
#' \deqn{y_d \mid \bar{z}_d, \eta, \sigma^2 \sim N(\bar{z}_d^\top \eta,\ \sigma^2).}
#'
#' This function performs one variational inference sweep with a parallel
#' document-level E-step and simple updates for the regression parameters.
#'
#' @param mod A list containing the current model state:
#'   \describe{
#'     \item{nd}{D×K matrix of document–topic counts.}
#'     \item{nw}{K×V matrix of topic–word counts.}
#'     \item{eta}{Numeric vector of length K; regression coefficients.}
#'     \item{sigma2}{Scalar noise variance for the Gaussian response.}
#'   }
#' @param docs IntegerMatrix of size NZ×3, where each row is a triple
#'   (d, v, c) in 0-based indexing: document index d, word index v,
#'   and count c = n_{d,v}. Rows with d outside [0, D-1] are ignored.
#' @param y NumericVector of length D; response y_d for each document.
#' @param ndsum IntegerVector of length D; total token count per document
#'   (i.e., ndsum[d] = sum_v n_{d,v}).
#' @param NZ Integer, number of non-zero entries in docs (rows of docs).
#' @param V Integer, vocabulary size.
#' @param K Integer, number of topics.
#' @param alpha Scalar Dirichlet prior parameter for document–topic
#'   distributions θ_d (symmetric prior with parameter α).
#' @param beta Scalar Dirichlet prior parameter for topic–word
#'   distributions β_k (symmetric prior with parameter β).
#' @param update_sigma Logical; if TRUE, update the noise variance σ²
#'   from residuals y_d - \bar{z}_d^\top \eta, otherwise keep σ² fixed.
#' @param tau Numeric, log-space cutoff used to prune very small topic
#'   responsibilities φ_{d,i,k} for numerical stability and efficiency.
#' @param show_progress Logical; if TRUE, print simple progress output
#'   during the E-step over documents.
#' @param chunk Integer, number of documents to process per parallel
#'   block in the E-step. Larger values reduce overhead but may use
#'   more memory.
#'
#' @return A list with updated variational parameters and diagnostics:
#'   \describe{
#'     \item{nd}{Updated D×K document–topic counts.}
#'     \item{nw}{Updated K×V topic–word counts.}
#'     \item{eta}{Updated K-dimensional regression coefficient vector.}
#'     \item{sigma2}{Updated scalar noise variance.}
#'     \item{elbo}{Scalar evidence lower bound (approximate).}
#'     \item{label_loglik}{Gaussian response log-likelihood component.}
#'   }
#'
stm_vi_parallel <- function(mod, docs, y, ndsum, NZ, V, K, alpha, beta, update_sigma = TRUE, tau = 20L, show_progress = TRUE, chunk = 5000L) {
    .Call(`_mlstm_stm_vi_parallel`, mod, docs, y, ndsum, NZ, V, K, alpha, beta, update_sigma, tau, show_progress, chunk)
}

